### ISSUE TITLE
When pymssql.connect() - DB-Lib error message 20002, severity 9;Adaptive Server connection failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#110]
```
READ FIRST Please (and then delete):

* Support requests should be posted here (not reported as bugs):
http://groups.google.com/group/pymssql
* 1.x branch of pymssql is no longer supported, please don't report bugs
for it

What steps will reproduce the problem?
1.I am trying to connect MS SQL server as below:
import pymssql
db = pymssql.connect(host='xxx',user='xxx',password='xxx',database='xxx')

What do you see?
I am getting the following error:

Traceback (most recent call last): File "XXX.py", line 2, in conn = 
pymssql.connect(host = 'XXX.com', user = 'xxx', password = 'xxx', database = 
'xxx') File "pymssql.pyx", line 556, in pymssql.connect (pymssql.c:7990) raise 
OperationalError(e[0]) OperationalError: (20017, 
'\xa0\xff\xaf\x02\x90_\x8d\x02L\xd6\xa7\x02\xda\xad;DB-Lib error message 20017, 
severity 9:\nUnexpected EOF from the server\nDB-Lib error message 20002, 
severity 9:\nAdaptive Server connection failed\n')

What version of the product are you using? On what operating system?
SQL Server 2012 database running on Windows Server 2008

Please provide any additional information below.

```

Original issue reported on code.google.com by `pav...@fairsetup.com` on 16 Jan 2013 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
This is a pretty generic connection error that could be caused by a lot of 
things outside of pymssql.

I'd recommend posting this instead as a topic on the discussion forum at 
http://groups.google.com/group/pymssql since it's not clear that this is a 
pymssql bug yet. You should mention in your posting what platform you are 
connecting from (e.g.: Linux, Mac, Windows, etc.), what version of Python 
you're using, how you installed pymssql (e.g.: `pip install pymssql` or `python 
setup.py` from code checked out from hg tip, etc.), what version of FreeTDS you 
have, etc.. I'd also be curious to know if you have tried connecting with other 
tools that use FreeTDS like osql or isql and what the results were.
```

Original comment by `msabr...@gmail.com` on 5 Feb 2013 at 6:50
- Changed state: **Invalid**
