### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'ChangeLog_highlights.rst'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#128]
```
Installed FreeTDS on Mac OS X 10.9 Mavericks using `brew install freetds`.

Created a requirements.txt file in my project with the following line:

pymssql>=2.0.0

Executed pip using the following arguments:

pip install --upgrade -r requirements.txt

Got the following output and error:

Downloading/unpacking pymssql>=2.0.0 (from -r requirements.txt (line 14))
  Using download cache from /Users/mark/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fp%2Fpymssql%2Fpymssql-2.0.0.tar.bz2
  Running setup.py egg_info for package pymssql
    setup.py: platform.system() => 'Darwin'
    setup.py: platform.architecture() => ('64bit', '')
    setup.py: platform.linux_distribution() => ('', '', '')
    setup.py: platform.libc_ver() => ('', '')
    setup.py: Detected Darwin/Mac OS X.
        You can install FreeTDS with Homebrew or MacPorts, or by downloading
        and compiling it yourself.

        Homebrew (http://brew.sh/)
        --------------------------
        brew install freetds

        MacPorts (http://www.macports.org/)
        -----------------------------------
        sudo port install freetds

    setup.py: Not using bundled FreeTDS
    setup.py: include_dirs = ['/usr/local/include']
    setup.py: library_dirs = ['/usr/local/lib']
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/mark/Virtualenvs/venv/build/pymssql/setup.py", line 412, in <module>
        long_description = open('README.rst').read() +"\n\n" + open('ChangeLog_highlights.rst').read(),
    IOError: [Errno 2] No such file or directory: 'ChangeLog_highlights.rst'
    Complete output from command python setup.py egg_info:
    setup.py: platform.system() => 'Darwin'

setup.py: platform.architecture() => ('64bit', '')

setup.py: platform.linux_distribution() => ('', '', '')

setup.py: platform.libc_ver() => ('', '')

setup.py: Detected Darwin/Mac OS X.

    You can install FreeTDS with Homebrew or MacPorts, or by downloading

    and compiling it yourself.



    Homebrew (http://brew.sh/)

    --------------------------

    brew install freetds



    MacPorts (http://www.macports.org/)

    -----------------------------------

    sudo port install freetds



setup.py: Not using bundled FreeTDS

setup.py: include_dirs = ['/usr/local/include']

setup.py: library_dirs = ['/usr/local/lib']

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/mark/Virtualenvs/venv/build/pymssql/setup.py", line 412, in <module>

    long_description = open('README.rst').read() +"\n\n" + open('ChangeLog_highlights.rst').read(),

IOError: [Errno 2] No such file or directory: 'ChangeLog_highlights.rst'

----------------------------------------

```

Original issue reported on code.google.com by `markaric...@gmail.com` on 26 Oct 2013 at 8:16

**Comment by GoogleCodeExporter** [comment]
```
I ran into the same thing installing version 2.0.0 on RHEL 6. I was able work 
around the problem by creating an empty ChangeLog_highlights.rst file.  I 
suppose this is no help when using brew though.

    pip install -b build pymssql=2.0.0
    cd build/pymssql
    touch ChangeLog_highlights.rst
    python setup.py build

```

Original comment by `fre...@gmail.com` on 13 Nov 2013 at 5:36
