### ISSUE TITLE
error establishing connection with server with Windows Authentication option enabled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#16]
```
What steps will reproduce the problem?
1. Log in workstationn MS XP Pro Version 2002 SP3
2. Install Python 2.6.5
3. Install pymssql from pymssql-1.9.908.win32-py2.6.exe
4. Open python shell from cmd with command python
5. >>>import pymssql
6. test on MSSQL server with authentication required
7. conn = pymssql.connect(host=r'BBB-DB-TEST\BBBTEST', trusted=False, 
database='WH', user='usr', password='usrxx77')
8. works fine no error messages
9. test on MSSQL server with Windows Authentication mode
10. conn = = pymssql.connect(host=r'WIN-DB-TEST\WINTEST', trusted=True, 
database='FTGDB')
11. get message Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 456, in pymssql.connect (pymssql.c:6016)
    raise InterfaceError(e[0])
pymssql.InterfaceError: Connection to the database failed for an unknown reason.

What is the expected output? What do you see instead?
expected output: None, or no error messages
I've got instead:
--------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 456, in pymssql.connect (pymssql.c:6016)
    raise InterfaceError(e[0])
pymssql.InterfaceError: Connection to the database failed for an unknown reason.
--------------------------------

What version of the product are you using? On what operating system?
- version: pymssql-1.9.908.win32-py2.6.exe
- OS: Windows XP Pro SP3

Please provide any additional information below.
- If I import pymssql or _mssql on IDLE shell it restarts. Command line python 
shell allows import these packages.
When tried to use _mssql instead of pymssql, gave same kind of errors.

also tried to make connection with following commands without success:
conn = = pymssql.connect(host=r'WIN-DB-TEST\WINTEST', trusted=True, 
database='FTGDB', user='', password='')
conn = = pymssql.connect(host=r'WIN-DB-TEST\WINTEST', trusted=True, 
database='FTGDB', user=None, password=None)
```

Original issue reported on code.google.com by `meestu...@gmail.com` on 18 Aug 2010 at 2:44

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue. I don't know how to fix it.
```

Original comment by `zhongqiu...@gmail.com` on 28 Aug 2010 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Windows auth doesn't work yet in 1.9; stick to 1.0.2 for now. Support for this 
is in progress, there are some problems though.
```

Original comment by `akuk...@gmail.com` on 21 Sep 2010 at 2:07
- Changed state: **Done**
