### ISSUE TITLE
Can't connect using pymssql 1.0.2 after upgrading FreeTDS from 0.64 to 0.83

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#28]
```
What steps will reproduce the problem?
1. install pymssql 1.0.2 linked against FreeTDS 0.83
2.
>>> conn = pymssql.connect(database='DATABASE',
...                                          host='SERVER:PORT',
...                                          user='USER',
...                                          password='PASSWD')

What is the expected output? What do you see instead?

Expected prompt with no error.  Got this instead:

Traceback (most recent call last):
  File "<stdin>", line 4, in ?
  File "/opt/app/g++lib6/python-2.4/lib/python2.4/site-packages/pymssql-1.0.2-py2.4-solaris-2.10-i86pc.egg.new/pymssql.py", line 609, in connect
    raise InterfaceError, e[0]
pymssql.InterfaceError: Connection to the database failed for an unknown reason.

What version of the product are you using? On what operating system?

pymssql 1.0.2, FreeTDS 0.83, Solaris10/Intel.

Please provide any additional information below.

This worked with FreeTDS 0.64 but it's getting old and lots of bugs have
been fixed in FreeTDS since its release.  After adjusting the tds version
in the  freetds.conf file I can connect successfully using both the 0.64
and 0.83 versions of tsql.

```

Original issue reported on code.google.com by `skip.mon...@gmail.com` on 5 Nov 2010 at 5:39

**Comment by GoogleCodeExporter** [comment]
```
I need to retract part of my submission.  As it turns out, we were running
pymssql 0.8.0.  I'm guessing there was some sort of API change between 0.8.0
and 1.0.2.  I'd appreciate pointers to documentation of such changes.

```

Original comment by `skip.mon...@gmail.com` on 5 Nov 2010 at 6:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `dam...@gmail.com` on 8 Mar 2011 at 3:31
- Added labels: **PyMssql-1.x**

**Comment by GoogleCodeExporter** [comment]
```
not supporting 1.x version.
```

Original comment by `rsyr...@gmail.com` on 8 Mar 2012 at 3:12
- Changed state: **WontFix**
