### ISSUE TITLE
Cannot connect under windows, works fine in linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#29]
```
What steps will reproduce the problem?
1. using 2.6 > try to connect under cmd line and get the 18456 state 1. nothing 
shows up other than user denied in the logs. 

What is the expected output? What do you see instead?
>>> conn = 
pymssql.connect(host=sqlhost,user=user,password=passwd,database=sqldatabase)
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    conn = pymssql.connect(host=sqlhost,user=user,password=passwd,database=sqldatabase)
  File "C:\Python26\lib\site-packages\pymssql.py", line 607, in connect
    raise OperationalError, e[0]
OperationalError: SQL Server message 18456, severity 14, state 1, line 0:
Login failed for user '*****'.

What version of the product are you using? On what operating system?
Windows XP, sp3 for both installs
archlinux

Please provide any additional information below.

I have tried on two different computers with the same results. one was in a vm 
which had a very basic install on it.
```

Original issue reported on code.google.com by `aupa...@gmail.com` on 27 Nov 2010 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
this is off a report server and I've tried locally on the server which is 
running 2003, and comes up with the same problem. 
```

Original comment by `aupa...@gmail.com` on 27 Nov 2010 at 7:54

**Comment by GoogleCodeExporter** [comment]
```
going through the doco I have since used the trusted argument in the connection 
function and this ends up working for me.

I have tried on sql2000 and sql 2005 express.
```

Original comment by `aupa...@gmail.com` on 27 Nov 2010 at 10:47

**Comment by GoogleCodeExporter** [comment]
Original comment by `dam...@gmail.com` on 8 Mar 2011 at 3:29
- Added labels: **PyMssql-Old**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dam...@gmail.com` on 8 Mar 2011 at 3:30
- Added labels: **PyMssql-1.x**
- Removed labels: **PyMssql-Old**

**Comment by GoogleCodeExporter** [comment]
```
not supporting 1.x version
```

Original comment by `rsyr...@gmail.com` on 8 Mar 2012 at 3:12
- Changed state: **WontFix**
