### ISSUE TITLE
_mssql.c: No such file or directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#3]
```
What steps will reproduce the problem?
1. Download pymssql-1.9.908.tar.gz
2. Try and build
3. Receive build error -> no _myssql.c
4. Pre-reqs are installed

What is the expected output? What do you see instead?
A clean build

What version of the product are you using? On what operating system?
1.9.908 on RedHat 2.6.9-67.ELsmp

Please provide any additional information below.
I've also tried this with an earlier source release 1.9.907 and the result
was the same.  Below is a snippet from the actual output:

sr/pkg/freetds/include -I/usr/local/include/python2.6 -c _mssql.c -o
build/temp.linux-i686-2.6/_mssql.o -DMSDBLIB
gcc: _mssql.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1

Below are the directory contents:

build         MANIFEST.in    pymssql.egg-info  setuptools-0.6c11-py2.6.egg
ChangeLog     _mssql.pxd     pymssql.pyx       sqlfront.pxd
ez_setup.py   _mssql.pyx     README            win32
ez_setup.pyc  nagios-plugin  setup.cfg
LICENSE       PKG-INFO       setup.py


```

Original issue reported on code.google.com by `mbroad...@gmail.com` on 29 Apr 2010 at 12:00

**Comment by GoogleCodeExporter** [comment]
```
I wasn't able to reproduce it with all of 3 different source packages.
Please provide the whole untrimmed output together with the command that you 
issue.
```

Original comment by `akuk...@gmail.com` on 29 Apr 2010 at 10:43
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
oraclep@cslxocat:(/home/oraclep/exe/pymssql-1.9.908):!:> python setup.py build

---------------------------------------------------------------------------
This script requires setuptools version 0.6c11 to run (even to display
help).  I will attempt to download it for you (from
http://pypi.python.org/packages/2.6/s/setuptools/), but
you may need to enable firewall access for this script first.
I will start the download in 15 seconds.

(Note: if this machine does not have network access, please obtain the file

   http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c11-py2.6.egg

and place it in this directory before rerunning this script.)
---------------------------------------------------------------------------
Downloading 
http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c11-py2.6.egg
running build
running build_ext
building '_mssql' extension
creating build
creating build/temp.linux-i686-2.6
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes
-fPIC -I/usr/local/include -I/usr/local/include/freetds -I/usr/include
-I/usr/include/freetds -I/usr/include/freetds_mssql -I/usr/local/freetds/include
-I/usr/pkg/freetds/include -I/usr/local/include/python2.6 -c _mssql.c -o
build/temp.linux-i686-2.6/_mssql.o -DMSDBLIB
gcc: _mssql.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1

```

Original comment by `mbroad...@gmail.com` on 4 May 2010 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
akukula any advice on this issue?  Thanks

-Mike
```

Original comment by `mbroad...@gmail.com` on 7 May 2010 at 4:40

**Comment by GoogleCodeExporter** [comment]
```
Here's my output.

[root@server pymssql-1.9.908]# python setup.py build
running build
running build_ext
cythoning _mssql.pyx to _mssql.c
building '_mssql' extension
creating build
creating build/temp.linux-i686-2.6
gcc -fno-strict-aliasing -DNDEBUG -O2 -g -pipe -Wformat .....

Your output lacks the 'cythoning ...' line, so it doesn't transform .pyx into 
.c and
that's obvious reason why it can't find it later. I'll try to figure out why it
doesn't catch that error and why it tries to proceed without that step. Probable
cause is that you don't have Cython installed. Anyway setup.py should detect 
that and
suggest appropriate action then abort.
```

Original comment by `akuk...@gmail.com` on 7 May 2010 at 5:31

**Comment by GoogleCodeExporter** [comment]
```
I checked and Cython is installed.  I re-installed it but still get similar 
issue. 
Here the output:

running build
running build_ext
building '_mssql' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes
-fPIC -I/usr/local/include -I/usr/local/include/freetds -I/usr/include
-I/usr/include/freetds -I/usr/include/freetds_mssql -I/usr/local/freetds/include
-I/usr/pkg/freetds/include -I/usr/local/include/python2.6 -c _mssql.c -o
build/temp.linux-i686-2.6/_mssql.o -DMSDBLIB
gcc: _mssql.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1

```

Original comment by `mbroad...@gmail.com` on 7 May 2010 at 10:05

**Comment by GoogleCodeExporter** [comment]
```
Would you be able to apply the attached patch to setup.py and try again?
```

Original comment by `akuk...@gmail.com` on 8 May 2010 at 6:52

Attachments:
- [setuppy.patch](https://storage.googleapis.com/google-code-attachments/pymssql/issue-3/comment-6/setuppy.patch)

**Comment by GoogleCodeExporter** [comment]
```
I performed the patch but still no joy. 

patch setup.py setuppy.patch
patching file setup.py
Hunk #1 succeeded at 30 (offset 3 lines).


running build
running build_ext
building '_mssql' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes
-fPIC -I/usr/local/include -I/usr/local/include/freetds -I/usr/include
-I/usr/include/freetds -I/usr/include/freetds_mssql -I/usr/local/freetds/include
-I/usr/pkg/freetds/include -I/usr/local/include/python2.6 -c _mssql.c -o
build/temp.linux-i686-2.6/_mssql.o -DMSDBLIB
gcc: _mssql.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1

```

Original comment by `mbroad...@gmail.com` on 10 May 2010 at 10:18

**Comment by GoogleCodeExporter** [comment]
```
> Hunk #1 succeeded at 30 (offset 3 lines).
Why is that? I made a patch on vanilla 1.9.908 sources from the following URL:
http://pymssql.googlecode.com/files/pymssql-1.9.908.tar.bz2
You shouldn't have any offsets on patching. Here's my results:

[root@server pymssql-1.9.908]# patch --verbose < setuppy.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- setup.py-orig      2010-04-28 12:11:06.000000000 +0200
|+++ setup.py   2010-05-07 19:52:40.833500472 +0200
--------------------------
Patching file setup.py using Plan A...
Hunk #1 succeeded at 27.
done

Are you sure you use unmodified 1.9.908 sources? Please try to download them 
from the
above URL to another empty directory and try to build them again.
```

Original comment by `akuk...@gmail.com` on 10 May 2010 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
I did as you suggested and things worked out a lot better:

oraclep@mybox:(/home/oraclep/exe/pymssql-1.9.908):!:> id
uid=0(root) gid=0(root) 
groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel)
oraclep@cslxocat:(/home/oraclep/exe/pymssql-1.9.908):!:> patch --verbose < 
setuppy.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- setup.py-orig      2010-04-28 12:11:06.000000000 +0200
|+++ setup.py   2010-05-07 19:52:40.833500472 +0200
--------------------------
Patching file setup.py using Plan A...
Hunk #1 succeeded at 27.
done
oraclep@cslxocat:(/home/oraclep/exe/pymssql-1.9.908):!:> python setup.py build
/usr/local/lib/python2.6/distutils/dist.py:266: UserWarning: Unknown 
distribution
option: 'zip_safe'
  warnings.warn(msg)
/usr/local/lib/python2.6/distutils/dist.py:266: UserWarning: Unknown 
distribution
option: 'setup_requires'
  warnings.warn(msg)
running build
running build_ext
cythoning _mssql.pyx to _mssql.c
building '_mssql' extension
creating build
creating build/temp.linux-i686-2.6
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes
-fPIC -I/usr/local/include -I/usr/local/include/freetds -I/usr/include
-I/usr/include/freetds -I/usr/include/freetds_mssql -I/usr/local/freetds/include
-I/usr/pkg/freetds/include -I/usr/local/include/python2.6 -c _mssql.c -o
build/temp.linux-i686-2.6/_mssql.o -DMSDBLIB
_mssql.c: In function `__pyx_pf_6_mssql_20MSSQLStoredProcedure_bind':
_mssql.c:9461: warning: '__pyx_v_rtc' might be used uninitialized in this 
function
creating build/lib.linux-i686-2.6
gcc -pthread -shared build/temp.linux-i686-2.6/_mssql.o -L/usr/local/lib
-L/usr/local/lib/freetds -L/usr/lib64 -L/usr/lib -L/usr/lib/freetds
-L/usr/lib/freetds_mssql -L/usr/local/freetds/lib -L/usr/pkg/freetds/lib 
-lsybdb -o
build/lib.linux-i686-2.6/_mssql.so
cythoning pymssql.pyx to pymssql.c
building 'pymssql' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes
-fPIC -I/usr/local/include -I/usr/local/include/freetds -I/usr/include
-I/usr/include/freetds -I/usr/include/freetds_mssql -I/usr/local/freetds/include
-I/usr/pkg/freetds/include -I/usr/local/include/python2.6 -c pymssql.c -o
build/temp.linux-i686-2.6/pymssql.o -DMSDBLIB
gcc -pthread -shared build/temp.linux-i686-2.6/pymssql.o -L/usr/local/lib
-L/usr/local/lib/freetds -L/usr/lib64 -L/usr/lib -L/usr/lib/freetds
-L/usr/lib/freetds_mssql -L/usr/local/freetds/lib -L/usr/pkg/freetds/lib 
-lsybdb -o
build/lib.linux-i686-2.6/pymssql.so
oraclep@cslxocat:(/home/oraclep/exe/pymssql-1.9.908):!:> python setup.py install
/usr/local/lib/python2.6/distutils/dist.py:266: UserWarning: Unknown 
distribution
option: 'zip_safe'
  warnings.warn(msg)
/usr/local/lib/python2.6/distutils/dist.py:266: UserWarning: Unknown 
distribution
option: 'setup_requires'
  warnings.warn(msg)
running install
running build
running build_ext
running install_lib
copying build/lib.linux-i686-2.6/pymssql.so -> 
/usr/local/lib/python2.6/site-packages
copying build/lib.linux-i686-2.6/_mssql.so -> 
/usr/local/lib/python2.6/site-packages
running install_data
copying _mssql.pyx -> /usr/local/
copying pymssql.pyx -> /usr/local/
running install_egg_info
Writing /usr/local/lib/python2.6/site-packages/pymssql-1.9.908-py2.6.egg-info

akukula I think we got it.
```

Original comment by `mbroad...@gmail.com` on 11 May 2010 at 4:59

**Comment by GoogleCodeExporter** [comment]
```
Akukula, not sure if this is related but here is something that's not allowing 
me to
utilize the modules. Python claims it can't locate the modules even though the 
shared
lib is in the path.

oraclep@cslxocat:(/home/oraclep):!:> python
Python 2.6.5 (r265:79063, Apr 27 2010, 09:29:02)
[GCC 3.4.6 20060404 (Red Hat 3.4.6-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libsybdb.so.5: cannot open shared object file: No such file or 
directory
>>> import sys
>>> list(sys.path)
['', '/usr/local/lib', '/usr/local/lib/python26.zip', 
'/usr/local/lib/python2.6',
'/usr/local/lib/python2.6/plat-linux2', '/usr/local/lib/python2.6/lib-tk',
'/usr/local/lib/python2.6/lib-old', '/usr/local/lib/python2.6/lib-dynload',
'/usr/local/lib/python2.6/site-packages']
>>> import _mssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libsybdb.so.5: cannot open shared object file: No such file or 
directory
>>> quit()
oraclep@cslxocat:(/home/oraclep):!:> locate libsybdb.so.5
/usr/local/lib/libsybdb.so.5
/usr/local/lib/libsybdb.so.5.0.0
/home/oraclep/exe/freetds-0.82/src/dblib/.libs/libsybdb.so.5
/home/oraclep/exe/freetds-0.82/src/dblib/.libs/libsybdb.so.5.0.0

oraclep@cslxocat:(/home/oraclep):!:> ll /usr/local/lib/libsybdb.so.5
lrwxrwxrwx  1 root root 17 Apr 27 16:15 /usr/local/lib/libsybdb.so.5 -> 
libsybdb.so.5.0.0
oraclep@cslxocat:(/home/oraclep):!:> ll /usr/local/lib/libsybdb.so.5.0.0
-rwxr-xr-x  1 root root 860869 Apr 27 16:15 /usr/local/lib/libsybdb.so.5.0.0


```

Original comment by `mbroad...@gmail.com` on 11 May 2010 at 5:53

**Comment by GoogleCodeExporter** [comment]
```
So it turned out that just a fresh download did the trick. The patch is not 
needed.
Unfortunately I can't tell why your system can't find the library that's 
obviously
installed. However, the original case can be closed.

```

Original comment by `akuk...@gmail.com` on 11 May 2010 at 7:28
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
I agree.  The original case can be closed.   As an addendum to this the 
original file
that was downloaded was a .gz file. Thanks for the assist. 
```

Original comment by `mbroad...@gmail.com` on 11 May 2010 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
[root@njvm117 ~]# python
Python 2.7 (r27:82500, Aug  5 2010, 15:06:54) 
[GCC 4.1.1 20070105 (Red Hat 4.1.1-52)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pymssql.py", line 30, in <module>
    import _mssql, types, string, time, datetime, warnings
ImportError: libsybdb.so.5: cannot open shared object file: No such file or 
directory
>>> import sys
>>> list(sys.path)
['', '/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg', 
'/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', 
'/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', 
'/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', 
'/usr/local/lib/python2.7/site-packages', '/usr/local/freetds/lib']
>>> import _mssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libsybdb.so.5: cannot open shared object file: No such file or 
directory
>>> quit()
[root@njvm117 ~]# locate libsybdb.so.5
/usr/local/freetds/lib/libsybdb.so.5
/usr/local/freetds/lib/libsybdb.so.5.0.0
[root@njvm117 ~]# ll /usr/local/freetds/lib/libsybdb.so.5
lrwxrwxrwx 1 root root 17 Aug  5 17:34 /usr/local/freetds/lib/libsybdb.so.5 -> 
libsybdb.so.5.0.0
[root@njvm117 ~]# ll /usr/local/freetds/lib/libsybdb.so.5.0.0
-rwxr-xr-x 1 root root 1044996 Aug  5 17:34 
/usr/local/freetds/lib/libsybdb.so.5.0.0

```

Original comment by `ryanko0...@gmail.com` on 9 Aug 2010 at 7:37

**Comment by GoogleCodeExporter** [comment]
```
just used this website: http://blog.365freshdays.com/?cat=7 for help. 
translated from chinese using google translate: 

Error:
ImportError: libsybdb.so.5: cannot open shared object file: No such file or 
directory

This is because we did not have installed freetds's lib path to 
LD_LIBRARY_PATH, modify ~ /. Bash_profile, add the command

export LD_LIBRARY_PATH = / home / demo / tools / freetds / lib: $ 
LD_LIBRARY_PATH
Save ~ /. Bash_profile revised, implementation of the source ~ /. Bash_profile, 
so that changes take effect

And should not be any problem.
```

Original comment by `ryanko0...@gmail.com` on 9 Aug 2010 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
and... i'm getting the problem again. sorry if this is a noob mistake -- really 
bugging me! 
```

Original comment by `ryanko0...@gmail.com` on 10 Aug 2010 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
I got the same problem, please help!
```

Original comment by `zx1...@gmail.com` on 26 Nov 2010 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
I could not fix the _mssql.c not found problem.

I am in Red Hat Enterprise Linux (RHEL 5.4)
and I have both python2.4 and python2.6

here were what I done:

0] yum install python26

1] yum install freetds

2] python2.6 ez_setup.py

3] easy_install-2.6 cython

4] easy_install-2.6 pymssql 
   I got -> 
   Downloading http://pymssql.googlecode.com/files/pymssql-1.9.908.win32.zip
Processing pymssql-1.9.908.win32.zip
error: Couldn't find a setup script in 
/tmp/easy_install-s3UIdY/pymssql-1.9.908.win32.zip
   <-

5] easy_install-2.6 http://pymssql.googlecode.com/files/pymssql-1.9.908.tar.gz
   I got ->
   gcc: _mssql.c: No such file or directory
gcc: no input files
error: Setup script exited with error: command 'gcc' failed with exit status 1
   <-

6] wget http://pymssql.googlecode.com/files/pymssql-1.9.908.tar.gz

7] tar zxvf pymssql* && cd pymssql*

8] python2.6 setup.py build
   I got ->
   /root/for-python/pymssql-1.9.908/_mssql.pyx:1286:26: undeclared name not builtin: strlen
building '_mssql' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -g -pipe -Wall 
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector 
--param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic 
-fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC 
-I/usr/local/include -I/usr/local/include/freetds -I/usr/include 
-I/usr/include/freetds -I/usr/include/freetds_mssql 
-I/usr/local/freetds/include -I/usr/pkg/freetds/include 
-I/usr/include/python2.6 -c _mssql.c -o build/temp.linux-i686-2.6/_mssql.o 
-DMSDBLIB
_mssql.c:1:2: error: #error Do not use this file, it is the result of a failed 
Cython compilation.
error: command 'gcc' failed with exit status 1
   <-

I almost crying :-(

I did not have /usr/local/include/freetds /usr/include /usr/include/freetds 
/usr/include/freetds_mssql /usr/local/freetds/include /usr/pkg/freetds/include

and I hadn't found anything like freetds_mssql  ....

what's wrong ??

please help :-(
```

Original comment by `zx1...@gmail.com` on 26 Nov 2010 at 7:18

**Comment by GoogleCodeExporter** [comment]
```
btw, I had patched the setuppy.patch file.
```

Original comment by `zx1...@gmail.com` on 26 Nov 2010 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
but if I do this:

0] yum install pymssql

1] python2.4

2] python shell
>>>import pymssql

it works!
why ? :-(
```

Original comment by `zx1...@gmail.com` on 26 Nov 2010 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
I had this same problem -- it seems that pymssql doesn't check for pyrex to be 
installed, and fails with this error if pyrex is missing.  I installed pyrex 
(easy_install pyrex), and pymssql installs properly now.
```

Original comment by `keith.sc...@gmail.com` on 21 Jan 2012 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
FYI, the latest version of pymssql requires Cython and does not use pyrex.
```

Original comment by `rsyr...@gmail.com` on 23 Jan 2012 at 4:42

**Comment by GoogleCodeExporter** [comment]
```
FYI: installing pyrex worked for me as well.
```

Original comment by `jason.hu...@gmail.com` on 24 Jan 2012 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
I can confirm installing pyrex did the trick, with version 2.0.0b1
```

Original comment by `hro.m...@gmail.com` on 9 Mar 2012 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
I had the same problem but installing cython then pyrex solved the issue.  
Also, you need to make sure that libsybdb is installed (through your system 
package manager as it's not a python library).   I suggest we modify the 
metadata for pip to require Cython and pyrex.   Since libsybdb is not a python 
package we can't work that through pip but perhaps we can print a warning if it 
isn't installed.
```

Original comment by `Philip.Z...@centuryinteractive.com` on 19 Mar 2012 at 5:29

**Comment by GoogleCodeExporter** [comment]
```
Ditto for me. `pip install -e 
'hg+https://code.google.com/p/pymssql/#egg=pymssql'` in a Python 2.6 virtualenv 
on OS X fails with `clang: error: no such file or directory: '_mssql.c'`. 
Installing pyrex resolves the issue.

This is very similar to other issues:

- issue 60
- issue 86

```

Original comment by `msabr...@gmail.com` on 7 Jan 2013 at 3:56
