### ISSUE TITLE
connection error with unknown reason on Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#48]
```
What steps will reproduce the problem?
1. install tdm-gcc 4.5.2 32bit version from http://tdm-gcc.tdragon.net/download
2. clone 7a55159b409b revision
3. modify setup.py as below
if sys.platform == 'win32':
    WINDOWS = True
    WIN32 = os.path.join(ROOT, 'win32')
    FREETDS = os.path.join(WIN32, 'freetds')
    include_dirs = [os.path.join(FREETDS, 'include')]
    library_dirs = [os.path.join(FREETDS, 'lib')]
    libraries = [
        #'libiconv', # <<< comment
        #'iconv', # <<< comment
        'sybdb',
        'ws2_32',
        'wsock32',
        'kernel32',
    ]
4. build and install the pymssql
python26 setup.py build -c mingw32 bdist_wininst

5. run the following script.
import pymssql
conn = pymssql.connect(server="myserver",
                user="myid", password="mypw", database="mydb")
cur = conn.cursor()
cur.execute("select * from mytable")

for row in cur:
    print row

What is the expected output? What do you see instead?
It is expected that contents of table is printed.
But, below error message occurred.

D:\prj\secu\TestWork\pymssql>python26 testpymssql.py
Traceback (most recent call last):
  File "testpymssql.py", line 4, in <module>
    user="tsaver", password="tsaveradmin", database="tsaver")
  File "pymssql.pyx", line 519, in pymssql.connect (pymssql.c:6697)
    raise InterfaceError(e[0])
pymssql.InterfaceError: Connection to the database failed for an unknown reason.

What version of the product are you using? On what operating system?
revision 7a55159b409b, Cython 0.14.1, Python 2.6.6, Windows 7

Please provide any additional information below.
Above script worked in CentOS 5.5 32bit well.
Also rev 237 build don't produce this issue on Windows.

```

Original issue reported on code.google.com by `marun...@gmail.com` on 18 Apr 2011 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
This issue may related with change of revision 46fde04e1e45.
When _mssql.pyx is changed as below, connection error don't occur.

@@ -460,8 +460,8 @@

         # add the port to the server string if it doesn't have one already and
         # if we are not using an instance
-        if ':' not in server and not instance:
-            server = '%s:%s' % (server, port)
+        #if ':' not in server and not instance:
+        #    server = '%s:%s' % (server, port)

         # override the HOST to be the portion without the server, otherwise
         # FreeTDS chokes when server still has the port definition.
@@ -470,10 +470,10 @@
         # doesn't get fixed for a while.  But if it does get fixed, this code
         # can be deleted.
         # patch: http://lists.ibiblio.org/pipermail/freetds/2011q2/026997.html
-        #if ':' in server:
-        #    os.environ['TDSHOST'] = server.split(':', 1)[0]
-        #else:
-        #    os.environ['TDSHOST'] = server
+        if ':' in server:
+            os.environ['TDSHOST'] = server.split(':', 1)[0]
+        else:
+            os.environ['TDSHOST'] = server

         # Add ourselves to the global connection list
         connection_object_list.append(self)
@@ -488,7 +488,8 @@
         dbsetlogintime(login_timeout)

         # Connect to the server
-        self.dbproc = dbopen(login, server)
+        #self.dbproc = dbopen(login, server)
+        self.dbproc = dbopen(login, '<pymssql dynamic>')

         # Frees the login record, can be called immediately after dbopen.
         dbloginfree(login)

```

Original comment by `marun...@gmail.com` on 18 Apr 2011 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
What version of FreeTDS are you using on Windows, the bundled version?  Its 
likely that was the cause.  A FreeTDS bug was preventing "host:port" from 
working correctly which is what is used internally by pymssql.  See this post:

http://lists.ibiblio.org/pipermail/freetds/2011q2/027004.html

Our bundled version of FreeTDS is out of date and likely does not have the bug 
fix.

You can test this by repacking the latest FreeTDS snapshot from freetds.org, 
zipping it, and replacing that int he pymssql source tree.  Then re-compile and 
I bet it works.

> Above script worked in CentOS 5.5 32bit well.

What version of FreeTDS were you using in CentOS?

```

Original comment by `rsyr...@gmail.com` on 25 Apr 2011 at 9:31
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I use the bundled version on Windows.
And I upgrade CentOS 5.6 and FreeTDS 0.64 is installed on CentOS 5.6.

I cannot download FreeTDS 
snapshot(ftp://ftp.ibiblio.org/pub/Linux/ALPHA/freetds/current/freetds-current.t
gz) from www.freetds.org.

So, I checkout source from CVS and try to build FreeTDS snapshot on MSYS and 
Cygwin.
To build, I refer to INSTALL.CVS document.
But, I cannot build FreeTDS with below Error on MSYS.
$ ./autogen.sh
running /bin/autoreconf in /d/prj/pysrc_build/freetds_cvs/freetds:
' is already registered with AC_CONFIG_FILES.
/usr/src/autoconf/autoconf-2.67/lib/autoconf/status.m4:290: AC_CONFIG_FILES is 
expanded from...
configure.ac:824: the top level
autom4te-2.67: /bin/m4 failed with exit status: 1
C:\devtool\MinGW\msys\1.0\bin\aclocal: /usr/bin/autom4te-2.67 failed with exit 
status: 1
autoreconf: aclocal failed with exit status: 1
' is already registered with AC_CONFIG_FILES.
/usr/src/autoconf/autoconf-2.67/lib/autoconf/status.m4:290: AC_CONFIG_FILES is 
expanded from...
configure.ac:824: the top level
autom4te-2.67: /bin/m4 failed with exit status: 1
C:\devtool\MinGW\msys\1.0\bin\aclocal: /usr/bin/autom4te-2.67 failed with exit 
status: 1
autoreconf: aclocal failed with exit status: 1

Same error occurred on Cygwin.

Do you know how to build FreeTDS on windows with MSYS or Cygwin?
```

Original comment by `marun...@gmail.com` on 26 Apr 2011 at 4:36

**Comment by GoogleCodeExporter** [comment]
```
I solved this issue using latest snapshot.
Thank you for your help.
The attached files are freetds.zip of latest snapshot build and installers for 
python 2.5/2.6.

I build FreeTDS snapshot using MSYS and tdm-gcc.
1. download http://ibiblio.org/pub/Linux/ALPHA/freetds/stable/freetds-0.91rc.tgz
2. $ export PATH=/c/devtool/mingw_tdm/bin/:$PATH
3. $ gcc -v
4. $ ./configure --prefix=/opt/freetds/freetds --enable-shared=no 
--enable-static=yes --enable-msdblib --enable-odbc-wide --with-tdsver=7.1 
5. $ make
6. $ make install
7. zip /opt/freetds/freetds folder to freetds.zip
8. replace win32\freetds.zip
9. d:\work\python26 setup.py build -c mingw32 bdist_wininst
```

Original comment by `marun...@gmail.com` on 27 Apr 2011 at 2:53

Attachments:
- [freetds.zip](https://storage.googleapis.com/google-code-attachments/pymssql/issue-48/comment-4/freetds.zip)
- [pymssql-1.9.909-dev.win32-py2.6.exe.7z](https://storage.googleapis.com/google-code-attachments/pymssql/issue-48/comment-4/pymssql-1.9.909-dev.win32-py2.6.exe.7z)
- [pymssql-1.9.909-dev.win32-py2.5.exe.7z](https://storage.googleapis.com/google-code-attachments/pymssql/issue-48/comment-4/pymssql-1.9.909-dev.win32-py2.5.exe.7z)

**Comment by GoogleCodeExporter** [comment]
```
Could it be possible to release a py2.7 version of this build ?

thx
```

Original comment by `arakim...@gmail.com` on 28 Aug 2011 at 9:50

**Comment by GoogleCodeExporter** [comment]
```
You can find the installer for py2.7 in issue 54.
```

Original comment by `marun...@gmail.com` on 29 Aug 2011 at 1:25

**Comment by GoogleCodeExporter** [comment]
```
tested && approuved ;)

Very thanks to you !
```

Original comment by `arakim...@gmail.com` on 30 Aug 2011 at 11:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `rsyr...@gmail.com` on 8 Mar 2012 at 3:18
- Changed state: **WontFix**
