### ISSUE TITLE
cursors returned from user defined functions lose connection?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#67]
```
What steps will reproduce the problem?
1. The following executes with no problem:  

<pre>
my_host="host"
my_user="username"
my_database=""
conn = 
pymssql.connect(host=my_host,user=my_user,trusted=True,database=my_database)
cur = conn.cursor()
result = cur.execute("select 1")
for row in result: print row
</pre>

2. but when the connection is made in a separate function and returned by that 
function, the connection isn't kept:

<pre>
def get_cursor(my_host,my_user,my_database):
    conn = pymssql.connect(host=my_host,user=my_user,trusted=True,database=my_database)
    cur = conn.cursor()
    return cur

if __name__ == "__main__":
  my_host="host"
  my_user="username"
  my_database="database"
  cur = get_cursor("tomax","RLannon","Odin")
  cur.execute("select 1")
</pre>

returns error: 

<pre>
Traceback (most recent call last):
  File "test_cur.py", line 13, in <module>
    cur.execute("select 1")
  File "C:\Python26\lib\site-packages\pymssql.py", line 198, in execute
    raise InterfaceError, e[0]
pymssql.InterfaceError: Not connected to any MS SQL server
</pre>


Python 2.6.2
pymssql 1.0.2
SQL Server 9.0.5266


Thanks for any help, hopefully I'm just dumb.

```

Original issue reported on code.google.com by `blan...@gmail.com` on 21 Sep 2011 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
I'm having the exact problem. The cursor is generated without errors, the 
problem comes when i try cursor.execute() Here is my setup:

Python 2.6.5
FreeTDS 0.82-6build1 (Ubuntu 10.04)
MSSQL Server 2008 Enterprise

The exception:

  File "/usr/lib/pymodules/python2.6/pymssql.py", line 198, in execute
    raise InterfaceError, e[0]
pymssql.InterfaceError: Not connected to any MS SQL server

```

Original comment by `timothy....@nis.ac.ke` on 4 Oct 2011 at 1:19

**Comment by GoogleCodeExporter** [comment]
```
Hey guys, pymssql 1.0.2 isn't really supported anymore.  There is new code in 
the HG repo that should be built against FreeTDS 0.91.  You will likely have 
more success going that route.
```

Original comment by `rsyr...@gmail.com` on 4 Oct 2011 at 4:53
- Changed state: **WontFix**
